Connect redux react
Ol-create/book-store pull request #3
Opened 2022-05-12 16:49 UTC by Ol-create

- Generate and add unique id to book
- Dispatch remove book function
- Dispatch checkStatus action
- UseSelector to compare state
- Add dispatch addBook function
- Add styles to button
- Add progress text align to center.

2022-05-12 18:59 UTC, rloterh requested changes
Hi Oluola, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Highlights 👍  
- Descriptive Pull Request
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._


<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 18:59 UTC, rloterh commented on src/components/Books.jsx
- [ ] `store` should be imported and the main React component `<App>` should be wrapped in _Provider_ and assign `store` in your _index.js_, similar to:

```ruby
    import store from './redux/configureStore';

    ReactDOM.render(
    <Provider store={store}>
        <App />
    </Provider>,
    document.getElementById('root')
    )
```

2022-05-12 18:59 UTC, rloterh commented on src/components/Books.jsx
Buttons for adding and removing possible, as well as checking status are missing! 
- [ ] Kindly ensure that books can be added and removed, and buttons are visible.
- [ ] Also, ensure that the button for checking the status on the categories is present and the page works as expected.

**Your Home page:**
![image](https://user-images.githubusercontent.com/12745474/168145976-9629bed4-d6a1-478c-8949-a15cb678062f.png)

**Your categories page:**
![image](https://user-images.githubusercontent.com/12745474/168147759-1d53fc16-73cd-4c81-a149-9aeb78111136.png)

2022-05-13 19:30 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey  @Ol-create 😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-05 02:36 UTC, merged